apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-camp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot-camp-app
  template:
    metadata:
      labels:
        app: boot-camp-app
      annotations:
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/port: "2112"
        metrics.dynatrace.com/path: "/metrics"
        logs.dynatrace.com/ingest: "true"
    spec:
      containers:
        - name: boot-camp-app
          image: alikingdom/boot-camp-app:1.1
          ports:
            - containerPort: 8080
            - containerPort: 2112
---
apiVersion: v1
kind: Service
metadata:
  name: boot-camp-app
spec:
  selector:
    app: boot-camp-app
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 8080 # container port
